### ISSUE TITLE
Crash sometimes when accessing an AE2 crafting terminal

### ISSUE THREAD

**Issue by Ozzymud** [JadedPacks/Agrarian-Skies-2#79]
Single player version 2.0.5

[crash-2020-03-22_06.10.15-client.txt](https://github.com/JadedPacks/Agrarian-Skies-2/files/4404010/crash-2020-03-22_06.10.15-client.txt)  

Happens randomly when accessing the terminal. Chickenbones closed the same issue way back in 2015 saying it was a bad NEI plugin but he was unsure which one. https://github.com/Chicken-Bones/NotEnoughItems/issues/135

**Comment by remclave** [comment]
It is a bad NEI plug-in that has never been fixed. As for random, it has been determined that it usually only happens once when a new instance of the mod pack is created or updated from a previous version. After the first crash, it appears the player can restart the game and the issue seems to correct itself.
