### ISSUE TITLE
Tear Jerker (onion) tool part issues

### ISSUE THREAD

**Issue by Ozzymud** [JadedPacks/Agrarian-Skies-2#82]
Single player v2.0.5

Some parts that have "Tear Jerker" listed as a valid material cannot be made out of it: 
![2020-03-30_16 28 28](https://user-images.githubusercontent.com/6426344/77971580-e676c300-72a3-11ea-9ed4-48ed35e85d6d.png) 

The pickaxe head and tool rod can be made from the ones I've tested. See screenshot above for patterns tested.

Some patterns seem to have 2 different "tear jerker" materials listed, one in purple the other in yellow, others only have the purple listed:

![2020-03-30_16 28 56](https://user-images.githubusercontent.com/6426344/77971665-250c7d80-72a4-11ea-86d3-599ef3797074.png)
![2020-03-30_16 28 51](https://user-images.githubusercontent.com/6426344/77971666-25a51400-72a4-11ea-87c4-7ac177e7ceed.png)

Onion seems to be an intended materal as it is listed on the patterns and there is even a reward that gives a mattock with an onion axe head.

**Comment by Ozzymud** [comment]
Noticed onion is listed twice in MaterialDefaults.cfg:

Line 509: 
    onion {
        I:attack=6
        S:color=light_purple
        I:durability=8
        D:handleModifier=0.30000001192092896
        I:harvestLevel=2
        I:miningSpeed=90
        I:reinforced=0
        D:shoddy=0.0
        D:xpAmount=1.0
    }

and line 485:

    materialonion {
        I:attack=6
        S:color=light_purple
        I:durability=8
        D:handleModifier=0.30000001192092896
        I:harvestLevel=2
        I:miningSpeed=90
        I:reinforced=0
        D:shoddy=0.0
        D:xpAmount=1.0
    }


restrictions.cfg lists:
        materialOnion:rod
        materialOnion:pickaxe
        materialOnion:hammerhead
        materialOnion:frypan

**Comment by remclave** [comment]
It's in there twice because one is a reference to reusing a previously made component being remade into another of the "restricted" components, like converting rods into a pickaxe head versus using the raw material "Onion" to make the parts. 

As for allowing more components, these will not be updated as the restrictions limit which recipes are allowed. It was done on purpose since the tear jerker tools selected as rewards early game were not intended to be replaced if the player loses them during game play. The restrictions show up as a twice-listed item with one in yellow text in the patterns.
